version: '3.8'

services:
  postgres:
    container_name: postgresdb
    build: ./docker/postgres
    image: postgresdb
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      dev:
        aliases:
          - ${DB_ALIAS}
    env_file:
      - .env
    volumes:
      - ./docker-data/postgres/data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/dat
    restart: always

  nodejs:
    container_name: nodejs
    build: ./docker/nodejs
    image: nodejs
    networks:
      dev:
        aliases:
          - ${APP_ALIAS}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
     - ${PORT}:3000
    command: yarn start:dev
    restart: always

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - ${RABBIT_PORT}:5672
      - ${RABBIT_INTERFACE_PORT}:15672
    networks:
      dev:
        aliases:
          - ${RABBIT_ALIAS}
networks:
  dev:
    external:
      name: dev